/* Author: Alexander Kellough
 * NetID: atk133
 * Compiler: GCC
 * Description:
 *      Call myRand.out to generate random numbers and file, open file, read random numbers, compute average.
 */
#include "hdrs.h"

// Union for int to string conversion
union STRI
{
    char bytes[4];
    int val;
};

int main()
{
    int status, fd, filenum, ret, sum;
    double average;
    char filename[12];
    union STRI in;
    
    // Fork child
    switch(fork()) 
    {
    case -1:
        perror("fork");
        exit(EXIT_FAILURE);
    case 0:
        // Execute myRand program (Takes no arguments)
        ret = execl("./myRand.out", "./myRand.out", NULL);
        if(ret == -1)
        {
            perror("exec");
            exit(EXIT_FAILURE);
        }
    }

    // wait for child to finish
    wait(&status);

    // get exit status
    if(WIFEXITED(status))
    {
       filenum = WEXITSTATUS(status); 
    }
    
    // Open filename generated by myRand
    sprintf(filename, "data%d.dat", filenum);
    fd = open(filename, O_RDONLY);
    
    if(fd == -1)
    {
        perror("open");
        exit(EXIT_FAILURE);
    }

    // Compute average
    for(int i = 0; i < 60; ++i)
    {
        ret = read(fd, in.bytes, 4); 
        if(ret == -1)
        {
            perror("read");
            exit(EXIT_FAILURE);
        }
        printf("%d\n", in.val);
        sum += in.val;
    }

    // Finish computing average (Double division for precision
    average = sum/60.0;

    // Display average, close file, exit
    printf("Average is: %f\n", average);
    close(fd);
    exit(EXIT_SUCCESS);
}
